### ISSUE TITLE
Incorporating SemiBin2?

### ISSUE THREAD

**Issue by julianzaugg** [rhysnewell/aviary#106]
Hey Rhys,

Just flagging that SemiBin2 was recently released (see https://academic.oup.com/bioinformatics/article/39/Supplement_1/i21/7210480), and it would appear to be superior to Semibin (version 1). Any motivation/time to incorporate this into Aviary (perhaps to replace version 1)?

**Comment by wwood** [comment]
Hey,

Good idea - but this is in the dev branch already thanks to @AroneyS , and will be in the next release.
ben

**Comment by julianzaugg** [comment]
Aha! Good to hear.
