### ISSUE TITLE
Quick note: shebang issue in Fasta_to_Scaffolds2Bin on the DAS_tool step

### ISSUE THREAD

**Issue by sternp** [rhysnewell/aviary#11]
The pipeline failed because the shebang in Fasta_to_Scaffolds2Bin.sh (#!/bin/env bash) doesn't work on my system, and may not work on others.

On Linux I believe env is normally in /usr/bin/

The following shebang worked for me:

#!/usr/bin/env bash

Just a quick note for future reference.

**Comment by rhysnewell** [comment]
That script comes from DASTool directly https://github.com/cmks/DAS_Tool/blob/master/src/Fasta_to_Scaffolds2Bin.sh

In the script there it has the correct shebang, so I'm not sure why it would have installed for you with the incorrect shebang?

**Comment by sternp** [comment]
Weird!

**Comment by sternp** [comment]
The correct shebang appears in the newer version of aviary. So hopefully a non-issue from now
