### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sternp** [rhysnewell/aviary#122]
Hey Rhys - sorry another small one, do you mind having a quick look? Andy has run into the same issue aswell, looks like a file of zero length is being generated.

```
[Fri Aug 25 06:10:45 2023]
rule prepare_binning_files:
    input: assembly/final_contigs.fasta
    output: data/maxbin.cov.list, data/coverm.cov
    jobid: 15
    reason: Missing output files: data/maxbin.cov.list, data/coverm.cov
    threads: 64
    resources: tmpdir=/data1/tmp

Activating conda environment: ../../../../conda/66a8b59755f121e40e3a82a9714b3ad5
Traceback (most recent call last):
  File "/mnt/hpccs01/work/microbiome/gordon/nanopore_assembly/aviary_output/barcode3/.snakemake/scripts/tmp9qm2t5ry.get_coverage.py", line 180, in <module>
    get_coverage(
  File "/mnt/hpccs01/work/microbiome/gordon/nanopore_assembly/aviary_output/barcode3/.snakemake/scripts/tmp9qm2t5ry.get_coverage.py", line 160, in get_coverage
    for i in range(len(cov_list[0])):
IndexError: list index out of range
[Fri Aug 25 06:10:46 2023]
Error in rule prepare_binning_files:
    jobid: 15
    output: data/maxbin.cov.list, data/coverm.cov
    conda-env: /mnt/hpccs01/work/microbiome/conda/66a8b59755f121e40e3a82a9714b3ad5

RuleException:
CalledProcessError in line 60 of /mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.7.1/aviary/aviary/modules/binning/binning.smk:
Command 'source /mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.7.1/bin/activate '/mnt/hpccs01/work/microbiome/conda/66a8b59755f121e40e3a82a9714b3ad5'; set -euo pipefail;  /mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.7.1/bin/python3.10 /mnt/hpccs01/work/microbiome/gordon/nanopore_assembly/aviary_output/barcode3/.snakemake/scripts/tmp9qm2t5ry.get_coverage.py' returned non-zero exit status 1.
  File "/mnt/hpccs01/work/microbiome/sw/aviary_repos/aviary-v0.7.1/aviary/aviary/modules/binning/binning.smk", line 60, in __rule_prepare_binning_files
  File "/mnt/hpccs01/work/microbiome/conda/envs/aviary-v0.7.1/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Removing output files of failed job prepare_binning_files since they might be corrupted:
data/maxbin.cov.list, data/coverm.cov
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
An error occurred
```

**Comment by rhysnewell** [comment]
This is a long read only run, right? Can you check if `data/long_cov.tsv` exists?
And can you send through the exact command?

If possible, could you also run coverm and see if it is actually generating an output? Using a command like this:
```
coverm contig -t {threads} -r {input_fasta} --single {' '.join(long_reads)} -p minimap2-ont -m length trimmed_mean variance --bam-file-cache-directory data/binning_bams/ --discard-unmapped --min-read-percent-identity 0.85 --output-file data/long_cov.tsv
```
Changing the threads, input_fasta, and long_reads as necessary?

**Comment by sternp** [comment]
Ah dang - looks like it is CoverM not mapping any reads. Ive heard this issue mentioned. Any idea how to fix?

```
[2023-08-24T20:10:17Z INFO  coverm::contig] In sample 'final_contigs.fasta/barcode3_combined.fastq.gz', found 0 reads mapped out of 6234441 total (0.00%)
```

**Comment by rhysnewell** [comment]
Yeah, thought it might be something like this. 

First, I'd check that the final_contigs.fasta file looks good and doesn't have any weird glitches happening in it. Then also check the reads, make sure the file is compressed correctly and nothing weird has happened. Then start playing around with the mapping parameters:

1. Double check all the paths are correct. 85% of the time I've seen people point out this issue it is because they have got their file paths mixed up.
2. Check if the final_contigs.fasta.fai exists and if it does, then delete it and let it regenerate with coverm or samtools faidx 
3. Try mapping directly with minimap2/bwa and see if it should be getting mapping results
4. If it should, then look at lowering the coverm parameters e.g. `min-aligned-fraction` `min-percent` etc.

**Comment by sternp** [comment]
Thanks Rhys I'll have to dig a bit further - potentially an issue with CoverM itself?

**First, I'd check that the final_contigs.fasta file looks good and doesn't have any weird glitches happening in it. Then also check the reads, make sure the file is compressed correctly and nothing weird has happened.** 
final_contigs.fasta is empty and the fastq looks fine

**Double check all the paths are correct. 85% of the time I've seen people point out this issue it is because they have got their file paths mixed up.**
Paths are okay.

**Check if the final_contigs.fasta.fai exists and if it does, then delete it and let it regenerate with coverm or samtools faidx**
Doesn't exist

**Try mapping directly with minimap2/bwa and see if it should be getting mapping results**
I will try this to confirm its CoverM

**If it should, then look at lowering the coverm parameters e.g. min-aligned-fraction min-percent etc.**
Parameters are very relaxed!
min-read-percent-identity 85%
Using min-covered-fraction 0%

**Comment by rhysnewell** [comment]
final_contigs.fasta is empty? That would be the issue then, did something go wrong during assembly?

**Comment by sternp** [comment]
UGH. I tracked it down to an IO error.

Sorry for wasting your time Rhys. Gotta love Lyra :)
