### ISSUE TITLE
Repeat experiment

### ISSUE THREAD

**Issue by MoroNesterov** [rhysnewell/aviary#130]
Hello. Question about the possibility of repeating the experiment. An array of data (long reads) was processed, first with the assemble command, then with the recover command, we got MAG in the final_bins folder. Over time, the same data was processed with the complete command, but the resulting MAG is somewhat different, what to do? Maybe it's in the aviary version?

**Comment by rhysnewell** [comment]
Hello, 

I assume you're also the person who sent me three emails in short succession to my gmail. Please have patience when asking questions.

Regarding your question, you can expect variation in binning results between runs. Most metagenomic binners are stochastic algorithms that have non-deterministic outputs. You might get slightly different results between each run, but the main results should stay the same.

Anyway, just chill out with the emails dude. Surely you can wait a day for me to give a reply.

Kind regards,
Rhys
