### ISSUE TITLE
Benchmark on CAMI2?

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#133]
Hello,

I was wondering if there exists a benchmark of Aviary on the CAMI2 datasets.

Thanks!

**Comment by rhysnewell** [comment]
Hi!

We did have some results floating around on the CAMI2 datasets awhile ago. The work can be found here in my thesis in chapter 5 (https://eprints.qut.edu.au/237953/1/Rhys%2BNewell%2BThesis(3).pdf)
There have been a some improvements made that would require us to redo the CAMI2 analyses, but you can use those results as a reference point.

Cheers,
Rhys

**Comment by Ge0rges** [comment]
Great! Thank you.
