### ISSUE TITLE
Decontamination in QC?

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#135]
I'm wondering if aviary at any point provides an option to remove contaminate reads from a host for example?

**Comment by rhysnewell** [comment]
You can use the `--reference-filter` flag to provide a genome that you would like to filter reads against. Reads that map to the reference will be removed

**Comment by Ge0rges** [comment]
Great thank you. It would be helpful to update the `-h` message as it is unclear that reads are `filtered out` by `helps in assembly`.

Can this flag be given GTDB taxIDs, or multiple genomes? For example, I'd like to filter out all eukaryotes.

**Comment by rhysnewell** [comment]
Currently it just takes a single reference genome, but it should be easy enough to make it capable of parsing multiple input genomes. In the meantime, you can just concatenate all of the genomes you wish to filter against into a single fasta file and provide that as input
