### ISSUE TITLE
Error with SPAdes

### ISSUE THREAD

**Issue by s-junguy** [rhysnewell/aviary#137]
Hi, I've got an issue with SPAdes. I use Illumina paired end libraries (10 GB per library) and this is my submission script:

#!/bin/bash
#SBATCH --cpus-per-task=4
#SBATCH --time=72:00:00
#SBATCH --partition=snowball
#SBATCH --ntasks=1
#SBATCH -o aviary.%j.%N.out
#SBATCH -e aviary.%j.%N.err
source /home/usr/miniconda3/bin/activate /home/usr/miniconda3/envs/aviary
cd testfastq
aviary complete -1 P19752_101_S33_L002_R1_001.fastq.gz -2 P19752_101_S33_L002_R2_001.fastq.gz

This is part of the output:

== Error ==  system call for: "['/home/s-junguy/miniconda3/3db6e60544ca5d9a19f02e6072527a26_/bin/spades-core', '/home/s-junguy/testfastq/data/short_read_assembly/K55/configs/config.info', '/home/s-junguy/testfastq/data/short_read_assembly/K55/configs/mda_mode.info', '/home/s-junguy/testfastq/data/short_read_assembly/K55/configs/meta_mode.info']" finished abnormally, OS return value: -9
None

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /home/s-junguy/testfastq/data/short_read_assembly/spades.log

Thank you for using SPAdes!
Queueing command spades.py --memory 250 --meta -t 8 -o data/short_read_assembly -1 /home/s-junguy/testfastq/P19752_101_S33_L002_R1_001.fastq.gz -2 /home/s-junguy/testfastq/P19752_101_S33_L002_R2_001.fastq.gz -k auto --tmp-dir /tmp
An error occurred

This is the error message:
09/07/2023 02:45:14 PM INFO: Time - 14:45:14 07-09-2023
09/07/2023 02:45:14 PM INFO: Command - /home/usr/miniconda3/envs/aviary/bin/aviary complete -1 P19752_101_S33_L002_R1_001.fastq.gz -2 P19752_101_S33_L002_R2_001.fastq.gz
09/07/2023 02:45:14 PM INFO: Version - 0.5.7
09/07/2023 02:45:14 PM WARNING: No assembly provided, assembly will be created using available reads...
09/07/2023 02:45:14 PM INFO: Configuration file written to /home/usr/testfastq/config.yaml
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=256000
Job stats:
job                                     count    min threads    max threads
-------------------------       -------  -------------  -------------
assemble_short_reads             1              8              8
complete_assembly_with_qc   1              1              1
complete_qc_short                  1              1              1
get_bam_indices                      1              8              8
move_spades_assembly           1              1              1
prepare_binning_files               1              8              8
total                                          6              1              8

Select jobs to execute...

[Thu Sep  7 14:45:40 2023]
rule assemble_short_reads:
    input: /home/usr/testfastq/P19752_101_S33_L002_R1_001.fastq.gz
    output: data/short_read_assembly/scaffolds.fasta, data/short_read_assembly
    jobid: 4
    benchmark: benchmarks/short_read_assembly_short.benchmark.txt
    reason: Missing output files: data/short_read_assembly/scaffolds.fasta
    threads: 8
    resources: mem_mb=256000, disk_mb=8609, tmpdir=/tmp

Activating conda environment: ../miniconda3/3db6e60544ca5d9a19f02e6072527a26_
Activating conda environment: ../miniconda3/3db6e60544ca5d9a19f02e6072527a26_
Waiting at most 5 seconds for missing files.
MissingOutputException in rule assemble_short_reads  in line 468 of /home/usr/aviary/aviary/modules/assembly/assembly.smk:
Job Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
data/short_read_assembly/scaffolds.fasta completed successfully, but some output files are missing. 4
Removing output files of failed job assemble_short_reads since they might be corrupted:
data/short_read_assembly
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2023-09-07T144516.052904.snakemake.log
09/09/2023 05:49:02 AM CRITICAL: Command 'snakemake --snakefile /home/usr/aviary/aviary/modules/Snakefile --directory /home/usr/testfastq --jobs 16 --rerun-incomplete   --configfile '/home/usr/testfastq/config.yaml' --nolock  --conda-frontend mamba --default-resources "tmpdir='/tmp'" --resources mem_mb=256000   --use-conda --conda-prefix ~/miniconda3   get_bam_indices' returned non-zero exit status 1.
slurmstepd-node301: error: Detected 1 oom-kill event(s) in StepId=1821875.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.

**Comment by rhysnewell** [comment]
Hey there,

Looks like you are using aviary 0.5.7, the most current released version is 0.7.2. However, there is currently unreleased code sitting on the dev branch that contains work that better handles job cluster submission thanks to @AroneyS, I'd recommend upgrading to the `dev` branch or waiting until we draft a new release which should happen very soon.

You could also try upgrading to 0.7.2 and see if that fixes your issue, but I'd strongly suggest using the latest code

**Comment by rhysnewell** [comment]
v0.8.0 also just got released, I would recommend upgrading via pip

**Comment by s-junguy** [comment]
Thank you. I upgraded the version successfully but I still got the same error.

**Comment by wwood** [comment]
Seems like you might need more RAm?

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by s-junguy** [comment]
Thank you. It was a RAM issue.
