### ISSUE TITLE
Run only QC?

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#138]
Hello,

I was wondering how it would be possible to run only the QC part of the assembly module?  I assume this would be using a variation of the `aviary recover -w` argument?

**Comment by rhysnewell** [comment]
You can set the target rule use `-w`. If you just want the qc to run and then exit, you would add `-w complete_qc_all` to your aviary command.
If you only have short reads: `-w complete_qc_short`
Only long reads: `-w complete_qc_long`
Both: `-w complete_qc_all`

**Comment by Ge0rges** [comment]
How can I access a list of the arguments available to the `-w` flag?

**Comment by rhysnewell** [comment]
Currently, that isn't directly available to users. Essentially any of the snakemake rules in the `.smk` files can be added as a target to the `-w` flag. For your cases, I believe all you would have to do is run aviary once with `-w flye_assembly`, then take the `assembly.fasta`, run your custom polishing, and then take that fasta and pass it into `recover`

There is the option to add gpu resource requests to rules, but that currently isn't enabled for the polishing step. We'll have a look at adding it in.

**Comment by Ge0rges** [comment]
Would doing so execute the assembly assessment, read mapping and coverage statistics modules?

**Comment by rhysnewell** [comment]
It should just run up until the flye assembly and then exit, but the it will remember that it finished at the flye_assembly rule and pickup from that point if you were to re-run without the workflow flag

**Comment by Ge0rges** [comment]
What would be the correct way to pass the polished assembly to the assemble command without the `-w` flag?

**Comment by rhysnewell** [comment]
You'd want to switch to the `recover` module. like this `aviary recover -a polished_assembly.fasta ...Extraflags...`

**Comment by Ge0rges** [comment]
Got it thank you, I hadn't picked up on the fact that the recover module would conduct the assembly assessment etc.

**Comment by rhysnewell** [comment]
I don't think it will generate the contig distributions, but you can run that yourself using `stats.sh polished_assembly.fasta`. I can make it apart of the recovery module in future though

**Comment by Ge0rges** [comment]
Thank you, for the tip. My use case is slightly odd as I need to use a separate machine to run medaka only...
