### ISSUE TITLE
Potential bug in medaka polishing call

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#146]
Hello again,

This just happened to me, so I thought I'd raise it as an issue to avoid a possible bug. However I am not familiar with snakemake and perhaps this does not apply. 

When calling medaka on a coassembly, the input reads should be all of the input reads. However the `-i` medaka flag does not accept a list of FASTQ files, which I believe is what is happening [here](https://github.com/rhysnewell/aviary/blob/53b27cb1896efce392bcdea2b4ed31535a1118c5/aviary/modules/assembly/scripts/polish.py#L369). This is based on medaka_consensus' argument parsing code [here](https://github.com/nanoporetech/medaka/blob/938167e2ff804899d578d04388ba5c15ab339316/scripts/medaka_consensus#L64C56-L64C56). I got around this by concatenating my FASTQ files.

**Comment by rhysnewell** [comment]
The script we use for medaka only ever takes a single assembly in as input, thanks for the heads up but I don't think this is relevant here
