### ISSUE TITLE
How to run create_aviary_webpage.py?

### ISSUE THREAD

**Issue by Ge0rges** [rhysnewell/aviary#151]
I have completed running aviary `assemble`, `annotate`, and `diversity` as separate steps. I am now looking through the final outputs. I noticed that aviary has a script that may present the final output nicely. I was wondering if/how to run `create_aviary_webpage.py` or if there are other plotting scripts within aviary? 

Moreover, is there a section in the docs that explains the aviary output directory?

**Comment by rhysnewell** [comment]
The webpage creation is currently unmaintained and a holdover from a much older version of Aviary. It's a lot of work to keep it updated for not much pay off so I don't think it will be put back into use anytime soon. Plotting and further analysis can be left up to the user

There is not currently a docs explanation for the output, but it can be added in. What specific questions do you have?

**Comment by Ge0rges** [comment]
Just what the expected output directories are from each command, and where the final results can be expected. For example, the bins directory has a lot of bib files with different suffixes, and an additional finals bins directory.

**Comment by rhysnewell** [comment]
The bins folder should contain the following files:
1. `bin_info.tsv` - a tab seprated file containing various metrics about the MAGs recovered by aviary. This includes N50 values, CheckM1 and 2 results, sample abundance info, GTDB taxonomy and a bunch of self-explanatory things that you can look at yourself.
2. `checkm_minimal.tsv` is just a simplified checkm results file for the bins
3. `coverm_abundances.tsv` is the relative abundances of each MAG in the samples you used during recovery.
4. `final_bins/` is a symlinked folder containing all of the MAGs recovered
5. `coverm.cov` is just coverage of the contigs in the assembly
6. `checkm2_output` is the output created when running checkm2

Did you look in the actual tsv files and read the header? It's all just standard MAG metrics

**Comment by Ge0rges** [comment]
Great thanks, I mostly wanted to know what the final list of directories/and files should look like for a successful run of the different `aviary`  commands.
