### ISSUE TITLE
singlem threads and 16

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#178]
Hey,

On a large-ish metagenome (~20Gbp) singlem_pipe_reads timed out in the queue. Since singlem pipe can make use of >1 thread (though tbf, improvements could be made), how come it is restricted to 1 thread?

Also, how come the binning methods are set to a maximum of 16 threads with e.g.
```
    threads:
        min(config["max_threads"], 16)
```
? If -t is >16, why not use more?

**Comment by rhysnewell** [comment]
I believe this was implemented to try and get the binners and assemblers to run in parallel, but I agree 16 threads is not enough. Probably just best to leave it out how it originally was and let them use max threads instead.

I'll look into the singlem pipe reads threading issue
