### ISSUE TITLE
binning only

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#185]
Hey,

It would be nice I think to have some official way of doing binning (+ checkm + gtdbtk) only - skipping abundances, singlem and whatever else we decide to add.

Right now that is just `-w recover_mags_no_singlem` ? Maybe add a `--binning-only` flag to make it more obvious?

**Comment by AroneyS** [comment]
`-w recover_mags_no_singlem` still runs abundances, currently need to also add `--skip-abundances`
