### ISSUE TITLE
skipping metabat

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#186]
Using metabat is generally a good idea because it is fast and often gives useful bins, but I'm confused by the help:

> --skip-binners.... # N.B. specifying "metabat" will skip both MetaBAT1 and MetaBAT2.

But then the inputs for das_tool:
```
rule das_tool:
    input:
...
        metabat_sspec = [] if "metabat_sspec" in config["skip_binners"] else "data/metabat_bins_sspec/done",
        metabat_spec = [] if "metabat_spec" in config["skip_binners"] else "data/metabat_bins_spec/done",
        metabat_ssens = [] if "metabat_ssens" in config["skip_binners"] else "data/metabat_bins_ssens/done",
        metabat_sense = [] if "metabat_sens" in config["skip_binners"] else "data/metabat_bins_sens/done",
```

Shouldn't it be something along the lines of
```
metabat_sspec = [] if "metabat_sspec" in config["skip_binners"] or 'metabat' in config['skip_binners'] else "data/metabat_bins_sspec/done",
...
```

?

**Comment by rhysnewell** [comment]
It should be, but looks that functionality didn't survive the refactoring that was done. It will get added back in

**Comment by wwood** [comment]
Oh maybe I misunderstoosd. I think that get converted into this kind of config with each specified:
```
skip_binners:
- concoct
- rosella
- vamb
- metabat_sens
- metabat_ssens
- metabat_spec
- metabat_sspec
- metabat2
```
So I think nothing to see here.
