### ISSUE TITLE
Snakemake doesn't respect umask value

### ISSUE THREAD

**Issue by AroneyS** [rhysnewell/aviary#188]
Looks like Snakemake uses a default umask of something like `077` so snakemake-created folders get permissions like `drwx------`.
Can we set manually with `os.umask(0o002)` at the start of the main Snakemake like in https://github.com/snakemake/snakemake/issues/2209?

**Comment by rhysnewell** [comment]
Seems like this would be the more valid solution as the OG solution missed the logs folder: https://github.com/snakemake/snakemake/issues/2209#issuecomment-1505691467

Using that would be fine, IMO. Slapping it into the entry Snakemake file should be fine
