### ISSUE TITLE
spades issues due to setuptools not specified in the env file

### ISSUE THREAD

**Issue by michoug** [rhysnewell/aviary#214]
Hi
I got this error exactly as described here

https://github.com/bioconda/bioconda-recipes/issues/49120

Updating spades to 4.0 and setuptools to v69 solved the issue

Best regards

**Comment by AroneyS** [comment]
@rhysnewell can we update spades? Looks like unicycler supports spades v4.0 now (https://github.com/rrwick/Unicycler/releases/tag/v0.5.1). Are there any other hold-ups?

**Comment by rhysnewell** [comment]
Looking through the releaase, I think we should be okay to upgrade. Doesn't seem like they had any obvious breaking changes to the CLI
