### ISSUE TITLE
recommended way to build conda envs

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#218]
Hi,

Kinda newbie thread of thought here.

I'm wanting to run several aviary runs in a snakefile in parallel, but don't want them all building conda envs y themselves. What is the recommendation for a separate step that builds the conda envs? Does `aviary recover --build` build everything necessary if the argument to build is missing?

I guess I'm looking for something like this to work
```
aviary recover --conda-prefix ~/e/aviary-conda-prefix --build
```
or specificalyl for short reads
```
aviary recover -1 dummy.fastq -2 dummy.fastq --build --conda-prefix ~/e/aviary-conda-prefix
```
But those both error out with missing input exceptions. Maybe --build should have a default?

Oh, it works when the input read files actually exist (maybe needs to handle that more gracefully).

Also is a bit confusing that there's a `[BUILD]` afterwards in the help. I interpreted that to mean a specific snakemake rule needs specifying. Maybe `[yes|no]`?

What about changing the help to

> Build conda environments necessary to run the pipeline, and then exit. Equivalent to \"--snakemake-cmds \'--conda-create-envs-only True \' \". Other inputs should be specified as if running normally so that the right set of conda environments is built.

?

**Comment by rhysnewell** [comment]
Yeah, ideally the build command would just build all of the environments without needing the read files but I unfortunately couldn't get snakemake to co-operate in that regard. The help message can be updated

**Comment by AroneyS** [comment]
I just used placeholder files to get Aviary conda env built in Bin Chicken (https://github.com/AroneyS/binchicken/blob/823bd135a945142cfb7c26d951616068d8e45e32/binchicken/binchicken.py#L1006)
