### ISSUE TITLE
--no-coassembly flag?

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#219]
Hey,

I reckon it is a little anti-intuitive that when multiple readsets are specified, that only the first is used for assembly by default.

WDYT about requiring users to explicitly use `--coassemble` or a new flag `--no-coassembly` for `recover` when no input assembly is given, otherwise erroring out? Just lost a day's compute time because I mistakenly didn't (modified the wrong script).

Thanks.

**Comment by rhysnewell** [comment]
I'd be open to adding in new flags, but I don't think coassembly should be the default
