### ISSUE TITLE
citations

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#22]
For future, be good to keep a citations section on github and/or within software so people have a list of the software used within that they can easily cite. Might be quite a few actually. 

Is the list just the ones in the flow diagram figure shown in the readme?
Thanks.

**Comment by rhysnewell** [comment]
Most of them would be in the flow diagram, but there are a few that are used by most tools like samtools and hts-seq libraries that should get cited as well. I'll compile these and add them in the README

**Comment by wwood** [comment]
sounds good - thanks.

**Comment by rhysnewell** [comment]
Citations are now added to `dev` readme, list will be updated as new modules are added
