### ISSUE TITLE
Update GTDB-Tk to version 2.0.0

### ISSUE THREAD

**Issue by julianzaugg** [rhysnewell/aviary#37]
GTDB-Tk has just been updated to version 2.0.0 [https://ecogenomics.github.io/GTDBTk/announcements.html](url). Could the gtdbtk yaml be updated to this version when possible?

**Comment by rhysnewell** [comment]
Yep, have there been any changes to the command line interface of GTDB-tk? I know it uses a new method to reduce resource consumption but not sure if that involved an interface overhaul or not

**Comment by rhysnewell** [comment]
Updated in b2c7c6aa10f7efe565559bff42f6f147c70370ec
Let me know if it gives you any issues, you'll have to update the database and subsequent aviary environment variables which I'm sure you are aware of

**Comment by julianzaugg** [comment]
Yep, thanks
