### ISSUE TITLE
install

### ISSUE THREAD

**Issue by Thexiyang** [rhysnewell/aviary#38]
Thanks for this nice tool! Do I understand right? Before I can use this pipeline, I need to first install each required tool firstly in my system? The current installation guideline did not give the instruction which tools we should install. Right?

**Comment by rhysnewell** [comment]
Thanks for giving Aviary a go!

Aviary will handle the installation of all tools via the use of conda and snakemake, so the only thing you need to install is aviary itself. As long as you create a valid conda environment using the provided `yaml` (https://github.com/rhysnewell/aviary/blob/master/aviary.yml) file and download and specify all of the required databases then Aviary should handle everything else for you.

**Comment by Thexiyang** [comment]
So upon first Aviary, we need to specify the databases that have been downloaded in the machine. Right? Any more details on where to download these databases?

**Comment by rhysnewell** [comment]
Yep, that's correct. I've added a section in the readme about which databses are considered required and which are optional: https://github.com/rhysnewell/aviary/blob/master/README.md#databases

Just remember that once you set your environment variables for the databases, you will have to reactivate the aviary conda environment or source your `.bashrc` in order for your machine to recognise those environment variables

**Comment by rhysnewell** [comment]
If this is sorted out for now, I'll go ahead and close this up. If you have any more questions, please feel free to reopen
