### ISSUE TITLE
Feature requests--flag MAGs with circular contigs and use CheckM output format 2 for final stats

### ISSUE THREAD

**Issue by StevenJRobbins** [rhysnewell/aviary#47]
Hey, just a friendly feature request. 

Feature 1) would it be possible to get the final checkM output in the final_bins dir in checkM output format 2? That gives a whole bunch of useful genome stats, like bin size, # contigs, GC content, longest contig, N50, etc. Super useful stuff downstream. It shouldn't cost much extra time since checkM has already been run, should just involve running "checkM qa --outfmt 2". 

Feature 2) If you decide to output a final metadata sheet that collates taxonomy, checkM stats (hopefully includes the outfmt 2 stats), relative abundance, etc, it would be awesome to have a field that includes whether the genome includes a circular contig, what the contig name is, AND how long the circular contig is--all stuff that's in Flye's assembly_info.tsv file. I'm finding some MAGs contain circular contigs that make up the bulk of the MAG (awesome!), but about half of the MAGs containing circular contigs just have smaller circular contigs that are likely misbinned plasmids or viruses. Would be very informative to flag in final output for those with long read data.

**Comment by rhysnewell** [comment]
Sounds reasonable, I'll add these in when I get a chance or if some intrepid contributor wants to give it a shot as well that would be good. Aviary already makes use of the circular contig stats so it wouldn't be so hard to add that in the final metadata

**Comment by rhysnewell** [comment]
Hey Steve,

Just wanted to flag that these features have all been added in v0.4.0 as well as your other requested feature, the ability to skip over some binners using the `--skip-binners` flag.

Just want to note that due to snakemake now requiring strict channel priority order many of the conda environments will likely have to be rebuilt upon first use.

Cheers,
Rhys

**Comment by rhysnewell** [comment]
Also, you can use SemiBin it's just by default turned off. They released a stable version so was safe to include it
