### ISSUE TITLE
pigz = 2.4

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#48]
Hey Rhys,

I went to install via conda as per instructions but could not mamba env create because "pigz 2.4 ... is excluded by strict repo priority". I fixed this by putting anaconda as the top priority channel, but I don't think that is probably the right thing to do. Is there some reason pigz is pinned?

**Comment by rhysnewell** [comment]
I think this is fixed by bumping the pinned version up to 2.6 which is actually hosted on conda-forge now, so the strict channel order will find it
