### ISSUE TITLE
README suggestions

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#50]
will eventually include and assembly stage and post binning analysis of MAGs 

guess that is out of date now?

Also it'd be helpful to link the environment variables to the websites where they can be downloaded ie where the official instructions are. Right now it just says point to a folder - not 100% clear what is supposed to be in those folders, esp EGGNOG

**Comment by rhysnewell** [comment]
Yeah, I'm in the process of overhauling the readme and the docs. They got a bit outdated, will get it sorted before I get the conda recipe working

**Comment by rhysnewell** [comment]
Hopefully the updated docs are more legible now and you can better understand what is required of the databases. Full docs are now here: https://rhysnewell.github.io/aviary/
