### ISSUE TITLE
Could not create conda environment 

### ISSUE THREAD

**Issue by uqmwu** [rhysnewell/aviary#51]
Hi 
I tried to use aviary to do assembly but got following errors:

07/16/2022 03:20:15 PM INFO: Version - 0.4.0
07/16/2022 03:20:15 PM INFO: Configuration file written to /scratch/project/alkane/Mengxiong/C3_anammox/aviary_assembly/config.yaml

07/16/2022 03:20:15 PM INFO: Executing: snakemake --snakefile /scratch/project_mnt/S0060/Mengxiong/aviary/aviary/modules/Snakefile --directory /scratch/project/alkane/Mengxiong/C3_anammox/aviary_assembly/ --jobs 16 --rerun-incomplete --configfile '/scratch/pr$
Building DAG of jobs...
Creating conda environment /scratch/project_mnt/S0060/Mengxiong/aviary/aviary/modules/binning/../../envs/coverm.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /scratch/project_mnt/S0060/Mengxiong/aviary/aviary/modules/binning/../../envs/coverm.yaml:
Command:
mamba env create --quiet --file "/scratch/project/alkane/Mengxiong/41aae5c655da25559509d205af987a3a.yaml" --prefix "/scratch/project/alkane/Mengxiong/41aae5c655da25559509d205af987a3a"
Output:
/bin/bash: /home/uqmwu4/bin/mamba: /home/conda/feedstock_root/build_artifacts/mamba-split_1649138419879/_h_env_pl: bad interpreter: No such file or directory

07/16/2022 03:20:21 PM CRITICAL: Command 'snakemake --snakefile /scratch/project_mnt/S0060/Mengxiong/aviary/aviary/modules/Snakefile --directory /scratch/project/alkane/Mengxiong/C3_anammox/aviary_assembly/ --jobs 16 --rerun-incomplete --configfile '/scratch/$

What is the issue here? Thanks!

**Comment by rhysnewell** [comment]
Hello!

`_h_env_pl: bad interpreter: No such file or directory` seems to indicate that python was potentially not installed properly. Could you walk me through how you installed aviary? And perhaps try reinstalling using the latest commit from the `master` branch

Cheers,
Rhys

**Comment by uqmwu** [comment]
Hi Rhys,

I just installed it via the guide you provided:

git clone https://github.com/rhysnewell/aviary.git
cd aviary
conda env create -n aviary -f aviary.yml
conda activate aviary
pip install -e .

How to reinstall via master branch? Thank you!

**Comment by rhysnewell** [comment]
Awesome, thanks. 

Could you please show me what your `.condarc` file looks like? You can find it in your home directory, e.g. `~/.condarc`

**Comment by uqmwu** [comment]
This is what .condarc looks like:
channels:
  - bioconda
  - conda-forge
  - defaults
  - ursky
channel_priority: strict
I followed the requirement steps you said to set up conda configuration.

**Comment by rhysnewell** [comment]
Okay, the order should be:
* conda-forge
* bioconda
* defaults
A mistake in the readme put bioconda be conda-forge. But I don't think that is your issue.

Could you please run `which python` and show me where it points to?
Also, can you try and run the python interpretter e.g. `python` -> then just run some random commands and see if it breaks

Have you also tried reinstalling python or creating a new conda environment?

**Comment by uqmwu** [comment]
the which python points to : ~/anaconda3/bin/python
I tried to run the python interpretter with some commands like input/ type, no problems.
The issue is caused by python so I need to reinstall python?

**Comment by rhysnewell** [comment]
It should point to the python installed within the aviary conda environment. Do you have the aviary environment activated?

**Comment by rhysnewell** [comment]
Okay, cool good to know. I'll go ahead and close this now.

Adding `conda activate` to your bashrc is not recommended. You should talk to your sysadmin about how best to get a conda environment to work with your PBS setup, but this might set you on the right path: https://stackoverflow.com/questions/53346159/running-qsub-with-anaconda-environment
