### ISSUE TITLE
Offline Installation

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#52]
Hi Rhys,

Aviary looks like a fantastic tool (I watched Ben's Abacus talk, the improvement over atlas, which I have used for my dataset, looks amazing).

My question is how is the best way to install aviary (namely all the snakemake environments and databases) on a HPC where I cannot access internet on the compute nodes, but only on the login node?

George

**Comment by rhysnewell** [comment]
Hi George!

Thanks, I'm glad you like the look of it. This is a good question that I've been thinking about in variations for awhile. So let me just clarify a few things in regards to your setup.

1) You have a node that you login to.
     - This is the node that you spawn jobs from using like qsub or pbs scripts from, right?
2) The jobs are then sent to the compute nodes which don't have internet access.
    - No internet access mean you can't just send one job and let it build the environments and then when it finishes you send the other jobs.

If this is all correct, then my suggestion would be that you use the `--build` command on an aviary run on the login node providing aviary with your given input files:
- This will build the DAG of all the jobs that need to be done, then make sure that all of the conda environments are accessible and correct. 
- If a conda environment does not exist yet but needs to, then aviary will build the environment.
- It will do this for all required rules but it will not exeute any code. So you don't need to worry about the login node getting incorrectly utilized.
- Once that is finished, then you should be able to send your jobs to your HPC queue:
    - This requires that the HPC nodes have access to your conda environments, which they should do.

Does that sound like it will work for you?

Cheers,
Rhys

**Comment by gbouras13** [comment]
That's correct Rhys - I submit via slurm on the login node, but I can't build environments on the compute node.

Your suggestions seem to work (I also don't have mamba - so am passing --conda-frontend conda also) for the assemble step , I will let you know if I have any other issues down the track.

George

**Comment by gbouras13** [comment]
Another comment  is perhaps it would be good to make it clear in the documentation what databases I need to download for GTDB and eggnog - I think I have them but I am not exactly sure.

I also think the eggnog hyperlink is broken.

George

**Comment by rhysnewell** [comment]
Thanks, I'll update these some more
