### ISSUE TITLE
Lorikeet Installation Fails 0.7.1

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#53]
Hi Rhys,

I managed to install aviary and all Conda environments (and everything else has run nicely on a test sample!) other than lorikeet. I get the following error:

CreateCondaEnvironmentException:
Could not create conda environment from /hpcfs/users/a1667917/myconda/envs/aviary/lib/python3.10/site-packages/aviary/modules/strain_analysis/envs/lorikeet.yaml:
Command:
conda env create --quiet --file "/hpcfs/users/a1667917/myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964.yaml" --prefix "/hpcfs/users/a1667917/myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964"
Output:
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - lorikeet-genome[version='>=0.7.1']

When I manually change lorikeet.yaml to 0.7.0 installation works, but then Lorikeet fails (probably why 0.7.1 is needed!)

George

**Comment by rhysnewell** [comment]
Hi George,

Thanks for your patience! I got the Lorikeet v0.7.1 approved for bioconda yesterday: https://github.com/bioconda/bioconda-recipes/pull/35877 but it would seem that it is still not quite yet available as searching for lorikeet yields only v0.7.0:

```terminal
n10853499:~$ mamba search lorikeet-genome

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Loading channels: done
# Name                       Version           Build  Channel
lorikeet-genome                0.3.2      h7826b6f_0  bioconda
lorikeet-genome                0.3.4      h7826b6f_0  bioconda
lorikeet-genome                0.3.5      h7826b6f_0  bioconda
lorikeet-genome                0.3.6      h7826b6f_0  bioconda
lorikeet-genome                0.3.6      h9eda3c7_1  bioconda
lorikeet-genome                0.3.7      h9eda3c7_0  bioconda
lorikeet-genome                0.3.7      h9eda3c7_1  bioconda
lorikeet-genome                0.4.0      h9eda3c7_0  bioconda
lorikeet-genome                0.5.0      h9eda3c7_0  bioconda
lorikeet-genome                0.6.6      haf990a0_0  bioconda
lorikeet-genome                0.7.0      haf990a0_0  bioconda
```

So we might just have to wait a little bit longer for the bioconda channel to sync up with the github pull requests. This can take some time, but if it takes more than two days I usually ask for some support.

Just out of interest, what was the error that lorikeet produced?

Also, you'll be safe to run every other step in the aviary pipeline except for the strain diversity analysis if you'd like to just get started on your assembly/binning

Cheers,
Rhys

**Comment by gbouras13** [comment]
Hi Rhys,

The error was indeed something like "lorikeet-genome 0.7.1 can't be found" - so I'd imagine you are correct. I will try again later today to see if it is available.

George

**Comment by gbouras13** [comment]
This is fixed now, the update must have pushed to bioconda.
