### ISSUE TITLE
lorikeet.smk snakemake typo

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#56]
rule lorikeet:
    input: bins/final_bins
    output: strain_diversity
    jobid: 0
    reason: Missing output files: strain_diversity
    threads: 32
    resources: tmpdir=/hpcfs/users/a1667917/tmp

Activating conda environment: ../../../myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964
Activating conda environment: ../../../myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964
Traceback (most recent call last):
  File "/hpcfs/users/a1667917/Kevin/aviary/S1/.snakemake/scripts/tmpazygu3hf.run_lorikeet.py", line 29, in <module>
    f"-p {snakemake.params.parallel_genome} {short_reads} {long_reads} -o {snakemake.output.output_directory}", shell=True).wait()
AttributeError: 'Params' object has no attribute 'parallel_genome'
[Thu Jul 21 09:46:36 2022]
Error in rule lorikeet:
    jobid: 0
    output: strain_diversity
    conda-env: /hpcfs/users/a1667917/myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964

RuleException:
CalledProcessError in line 71 of /hpcfs/users/a1667917/myconda/envs/aviary/lib/python3.10/site-packages/aviary/modules/strain_analysis/strain_analysis.smk:
Command 'source /hpcfs/users/a1667917/myconda/envs/aviary/bin/activate '/hpcfs/users/a1667917/myconda/envs/aviary/fcd3e55b2a2091296105e8c2f42ee964'; set -euo pipefail;  python /hpcfs/users/a1667917/Kevin/aviary/S1/.snakemake/scripts/tmpazygu3hf.run_lorikeet.py' returned non-zero exit status 1.
  File "/hpcfs/users/a1667917/myconda/envs/aviary/lib/python3.10/site-packages/aviary/modules/strain_analysis/strain_analysis.smk", line 71, in __rule_lorikeet
  File "/hpcfs/users/a1667917/myconda/envs/aviary/lib/python3.10/concurrent/futures/thread.py", line 58, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

And when I look at the Snakemake rule, the param is defined as "parallel_genomes"

When I fixed this it solved the issue.

George

**Comment by rhysnewell** [comment]
Thanks, I'll fix this up in the next commit
