### ISSUE TITLE
Potential duplication of contigs occuring [Probably false alarm]

### ISSUE THREAD

**Issue by rhysnewell** [rhysnewell/aviary#59]
Leaving this here, I've found some duplicated contigs on some recent runs of aviary. Please avoid using until I sort out where the bug was introduced. Once this is closed then feel free to use

**Comment by rhysnewell** [comment]
Looks like i'm dumb, nevermind

**Comment by julianzaugg** [comment]
I just noticed this issue in one of my samples:
```bash
...01_S196/data/refined_bins/final_bins$ grep "NODE_11051_length_5807_cov_0.557042" *
vamb_bins.tsv.024_sub.fna:>NODE_11051_length_5807_cov_0.557042
vamb_bins.tsv.028_sub.fna:>NODE_11051_length_5807_cov_0.557042
```
Do you recall what the cause was in your case?
