### ISSUE TITLE
finalize_stats and get_abundances does not seem to be in the DAG

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#61]
Thought I'd make a new issue instead of continuing in #54.

Just to summarise, the full pipeline is not running to completion for me, I don't have 'bin_info.tsv', 'coverm_abundances.tsv' 'checkm_minimal.tsv' or 'done' in my output bins directory, only 'checkm.out' and a symlink to the final_bins directory - so when I run aviary cluster it does not work.

I had the same issue prior to the update with checkm2 and also afterwards so I don't think it is related to that either. 

I have attached the log file. The only issue I see  (prior to lorikeet) is that vamb and rosella run even though I specify "--skip-binners vamb rosella". Rosella completes with no error anyway, vamb errors which is why I skip it. 

Regardless, the rules finalise_stats and get_abundances aren't in the DAG to begin with at all so I'm not sure that is causing the issue.

[13748891_aviary.err.txt](https://github.com/rhysnewell/aviary/files/9177241/13748891_aviary.err.txt).

**Comment by rhysnewell** [comment]
To the best of my knowledge this should be fixed on the main branch. Using the `complete` subcommand will now actually give you a complete output. Using skip-binners should now also skip those binners even if a new assembly is built
