### ISSUE TITLE
singlem 

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#62]
Hi Rhys,

The fix for #61 certainly worked - everything in the recover_mags module ran well on a re-run for me until the last 2 steps. All the files mentioned in #61 in the bins directory are created.

Alas, there seems to be an issue with singlem_appraise, specifically in the plot generation:

rule singlem_appraise:
    input: data/singlem_out/metagenome.combined_otu_table.csv, data/gtdbtk/done, bins/checkm.out
    output: data/singlem_out/singlem_appraise.svg
    jobid: 30
    reason: Missing output files: data/singlem_out/singlem_appraise.svg; Input files updated by another job: data/gtdbtk/done, bins/checkm.out, data/singlem_out/metagenome.combined_otu_table.csv
    threads: 32
    resources: tmpdir=/hpcfs/users/a1667917/tmp

Activating conda environment: ../../../myconda/envs/aviary/4c5875ddb0cf690b54611fae9c7a7e68
07/25/2022 04:17:09 PM INFO: Using as input 3 different sequence files e.g. bins/final_bins/concoct_bins.tsv.004.fna
07/25/2022 04:17:09 PM INFO: Searching with 14 SingleM package(s)
07/25/2022 04:17:09 PM INFO: Searching for reads matching 28 different protein HMM(s)
07/25/2022 04:17:11 PM INFO: Finished search phase
07/25/2022 04:17:11 PM INFO: Running separate alignments in GraftM..
07/25/2022 04:17:15 PM INFO: Finished extracting aligned sequences
07/25/2022 04:17:15 PM INFO: Running taxonomic assignment with GraftM..
07/25/2022 04:22:39 PM INFO: Finished running taxonomic assignment with GraftM
07/25/2022 04:22:39 PM INFO: Finished
07/25/2022 04:22:42 PM INFO: Using as input 1 different sequence files e.g. assembly/final_contigs.fasta
07/25/2022 04:22:42 PM INFO: Searching with 14 SingleM package(s)
07/25/2022 04:22:42 PM INFO: Searching for reads matching 28 different protein HMM(s)
07/25/2022 04:22:44 PM INFO: Finished search phase
07/25/2022 04:22:44 PM INFO: Running separate alignments in GraftM..
07/25/2022 04:22:48 PM INFO: Finished extracting aligned sequences
07/25/2022 04:22:48 PM INFO: Running taxonomic assignment with GraftM..
07/25/2022 04:28:11 PM INFO: Finished running taxonomic assignment with GraftM
07/25/2022 04:28:11 PM INFO: Finished
07/25/2022 04:28:14 PM INFO: Read in 29 markers from the different genomes
07/25/2022 04:28:14 PM INFO: After excluding duplicate markers that may indicate contamination, found 27 markers
07/25/2022 04:28:14 PM INFO: Read in 27 unique sequences from the 2 reference genomes
07/25/2022 04:28:14 PM INFO: Generating plot for marker: S1.12.ribosomal_protein_S12_S23
Traceback (most recent call last):
  File "/hpcfs/users/a1667917/myconda/envs/aviary/4c5875ddb0cf690b54611fae9c7a7e68/bin/singlem", line 744, in <module>
    output_svg=args.plot)
  File "/hpcfs/users/a1667917/myconda/envs/aviary/4c5875ddb0cf690b54611fae9c7a7e68/lib/python3.6/site-packages/singlem/appraisal_result.py", line 86, in plot
    doing_binning)
  File "/hpcfs/users/a1667917/myconda/envs/aviary/4c5875ddb0cf690b54611fae9c7a7e68/lib/python3.6/site-packages/singlem/appraisal_result.py", line 269, in _plot_gene
    self._plot_scale(axis, max_total_count)
  File "/hpcfs/users/a1667917/myconda/envs/aviary/4c5875ddb0cf690b54611fae9c7a7e68/lib/python3.6/site-packages/singlem/appraisal_result.py", line 352, in _plot_scale
    overlap = (ylim[1]-ylim[0]-sum(sides))/(len(sides)-1)
ZeroDivisionError: float division by zero
[Mon Jul 25 16:28:14 2022]
Error in rule singlem_appraise:
    jobid: 30
    output: data/singlem_out/singlem_appraise.svg
    conda-env: /hpcfs/users/a1667917/myconda/envs/aviary/4c5875ddb0cf690b54611fae9c7a7e68
    shell:
        singlem pipe --threads 32 --sequences bins/final_bins/*.fna --otu_table data/singlem_out/genomes.otu_table.csv; singlem pipe --threads 32 --sequences assembly/final_contigs.fasta --otu_table data/singlem_out/assembly.otu_table.csv; singlem appraise --metagenome_otu_tables data/singlem_out/metagenome.combined_otu_table.csv --genome_otu_tables data/singlem_out/genomes.otu_table.csv --assembly_otu_table data/singlem_out/assembly.otu_table.csv --plot data/singlem_out/singlem_appraise.svg --output_binned_otu_table data/singlem_out/binned.otu_table.csv --output_unbinned_otu_table data/singlem_out/unbinned.otu_table.csv > data/singlem_out/singlem_appraisal.tsv
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

All the csvs seem to be created in the output (some are size 0).

George

**Comment by rhysnewell** [comment]
This looks to be an issue with SingleM when the input files are empty due to samples not containing detectable diversity. Did the samples that fail have only a few MAGs recovered from them?

I'll add a graceful error and exit for singleM to prevent this from happening in future

Rhys

**Comment by gbouras13** [comment]
One sample that failed had 3, another seems to have worked and had 13. 

So this is probably the reason. Thanks again Rhys.

George

**Comment by rhysnewell** [comment]
SingleM should no longer cause aviary to crash if it fails to produce the final plot I think, so closing this now
