### ISSUE TITLE
Error when run aviary: ModuleNotFoundError: No module named 'aviary.config'

### ISSUE THREAD

**Issue by kevinzhongxu** [rhysnewell/aviary#63]
Hi there, 
I just installed the aviary following exactly the instructions. But, error occurred when I run aviary. It indicates that the missing cou of "aviary.config" as you could see below the error message. Please help. Thanks!

Kevin

#######################################################
Successfully installed aviary-genome-0.4.2 ruamel.yaml-0.17.21
(aviary1) [xxxxxx@login03 aviary]$ 
(aviary1) [xxxxxx@login03 aviary]$ aviary --help
Traceback (most recent call last):
  File "/home/xxxxxx/.local/bin/aviary", line 7, in <module>
    from aviary.aviary import main
  File "/home/xxxxxx/.local/lib/python3.8/site-packages/aviary/aviary.py", line 20, in <module>
    import aviary.config.config as Config
ModuleNotFoundError: No module named 'aviary.config'
#######################################################

**Comment by rhysnewell** [comment]
Hi Kevin,

Thanks for trying out Aviary!
I have seen this before,  it occurred for me when I used pip to install aviary from the github repo. I'm not sure what causes it though.

Did you install aviary from conda or the github repo?

Installing from pip made it go away i.e. `pip install aviary-genome` You may have to uninstall aviary first

Let me know if that works.

Cheers,
Rhys

**Comment by kevinzhongxu** [comment]
Hi Rhys,

Thanks for the prompt reply! I tried using pip install aviary-genome, but
still get the same error as previously (ModuleNotFoundError: No module
named 'aviary.config'). I noted there's warning after I pip install, and I
wonder whether this is the reason cause missing aviary.config....

###################33
DEPRECATION: Configuring installation scheme with distutils config files is
deprecated and will no longer work in the near future. If you are using a
Homebrew or Linuxbrew Python, please see discussion at
https://github.com/Homebrew/homebrew-core/issues/76621
####################

Thanks,
Kevin

**Comment by rhysnewell** [comment]
Hi Kevin,

I was able to replicate your issue. Looks like the published pip package is just missing all of the aviary code for some reason, seems to be an issue with how the distribution was built. I'll look into it.

The deprecation warning you posted is for something else, unrelated to aviary. Thank you though

In the meantime, if you would like to use aviary I encourage you to try installing it via option 3. It will work just as well as the other options and will suffice until I get the distributions packaging correctly.

Cheers,
Rhys

**Comment by kevinzhongxu** [comment]
Hi Rhys,

Noted! Looking forward to your fixation. Thank you!

Thanks
Kevin

**Comment by rhysnewell** [comment]
Please note, when install from github it might be best to use `pip install -e .` rather than `pip install .`, since pip might incorrectly package aviary again

**Comment by kevinzhongxu** [comment]
Ok

**Comment by kevinzhongxu** [comment]
Wow, it's fixed. I just tried the 3rd option, and used "pip3 install -e ."

Thank you!
Kevin

**Comment by rhysnewell** [comment]
I found a fix for this. Aviary v0.4.3 will be properly installable I think. I'll reopen if it is not

**Comment by kevinzhongxu** [comment]
Cool!
