### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by cbrueffer** [rhysnewell/aviary#64]
The license situation in this repo is confusing:

- LICENSE (and thus Github) says BSD-3-Clause
- README says GPL3
- setup.py says GPL3

Would be great if this could be clarified.

Found while looking at the update PR in Bioconda (https://github.com/bioconda/bioconda-recipes/pull/36233) where the software is marked GPL3.

**Comment by rhysnewell** [comment]
The license has been changed to GPL3, thank you for pointing this out
