### ISSUE TITLE
The /home/ directory is quickly filled up and result in the stop of aviary with error at step of coverM ("ERROR coverM::bamgenerator"). 

### ISSUE THREAD

**Issue by kevinzhongxu** [rhysnewell/aviary#65]
Hi there, 

I'm running aviary on a server shared by many users and have a limited /home/ directory (up to 400Gb). My aviary conda environment is installed in /home/MyAccount/.conda/envs/aviary/. When I run aviary, the /home/ directory is quickly filled up and resulting the stop of aviary with error at step of coverM ("ERROR coverM::bamgenerator"). Do you have a clue about this? Did I install or configure correctly? Now the annoying part is that the /home/ is full and I do not know how to free the space because I can not see these trash neither in my folder nor in others including the hidden folder. Please help, Thank you!

Kevin

$sudo df -h /home
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdt1       413G  360G   33G  92% /

$sudo du -sh /home
208G	/home

**Comment by rhysnewell** [comment]
Hi Kevin,

Are you also installing the databases within your home directory? 400 Gb seems excessive for the conda environments, but the databases can be quite large and require a lot of disk space. Is it possible to talk to your sysadmins about creating a shared space to install the databases and conda environments too that everyone can access?
Additionally, what is the error that is being returned by CoverM?

Cheers,
Rhys

**Comment by kevinzhongxu** [comment]
Hi Rhys,

The database is installed somewhere but not in /home, and my conda
environment is only ~2Gb in size. You can see attached, the error is "ERROR
coverM::bamgenerator". Yeap, I'm contacting our sysadmins as well.

Thanks,
Kevin

**Comment by rhysnewell** [comment]
Hi Kevin,

You need to post the error output on to GitHub for me to see it, you can't post it via e-mail. 
It would seem that you need to free up some space in your home drive though, the conda environments are not the issue here. Does you server system have a scratch space for users to work with large files?

Cheers,
Rhys

**Comment by kevinzhongxu** [comment]
Hi Rhys,

I will add the error message to the web.
Yes, there is a ~400Gb /scratch space. And also, we have a big work space
(/data/) with ~100Tb in size.

Thanks,
Kevin

**Comment by rhysnewell** [comment]
Hi Kevin,

Sorry for not getting back to you, I've been on leave. I think you should be making use of the other storage space on your server and not working within your home directory. I don't think this is the fault of aviary, as it appears your home directory was already very full. Either clear up space in your home directory or use the data or scratch space on your server and then transfer the results when aviary has finished.

Cheers,
Rhys

**Comment by kevinzhongxu** [comment]
Thank you, Rhys!
