### ISSUE TITLE
Exporting environmental CHECKM2DB does not work?

### ISSUE THREAD

**Issue by julianzaugg** [rhysnewell/aviary#66]
I received the following error while running `aviary recover` (version `0.4.3`), even after defining the environmental variable `CHECKM2DB`

```
Activating conda environment: ../../../../../home/user/.conda/envs/c794e5a97a89d3794674035f5793a0dc
Using CheckM2 database /srv/db/checkm2_data/0.1.2/uniref100.KO.1.dmnd
[08/15/2022 05:08:50 PM] INFO: Running quality prediction workflow with 60 threads.
[08/15/2022 05:08:50 PM] WARNING: Database not found using the environmental variable: CHECKM2DB. Please fix your $PATH. Using internal database path instead.
[08/15/2022 05:08:50 PM] ERROR: DIAMOND database not found. Please download database using <checkm2 database --download>
[Mon Aug 15 17:08:51 2022]
Error in rule checkm_rosella:
    jobid: 17
    output: data/rosella_bins/checkm2_out, data/rosella_bins/checkm.out
    conda-env: /srv/home/user/.conda/envs/c794e5a97a89d3794674035f5793a0dc
    shell:
        touch data/rosella_bins/checkm.out; export CHECKM2DB=/srv/db/checkm2_data/0.1.2/uniref100.KO.1.dmnd; echo "Using CheckM2 database $CHECKM2DB"; checkm2 predict -i data/rosella_bins// -x fna -o data/rosella_bins/checkm2_out -t 60 --force; cp data/rosella_bins/checkm2_out/quality_report.tsv data/rosella_bins/checkm.out
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job checkm_rosella since they might be corrupted:
data/rosella_bins/checkm2_out, data/rosella_bins/checkm.out
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Setting the path with the `--checkm2_db_path  /srv/db/checkm2_data/0.1.3/CheckM2_database` parameter does, however, work.

**Comment by rhysnewell** [comment]
Odd, I'll have to have a look at this when I get back. Kind of bizarre it's working one but not the other, they both do the same thing

**Comment by julianzaugg** [comment]
It was only a quick test while assisting someone, so potentially I am mistaken :)

**Comment by rhysnewell** [comment]
Oh, I found your error. The paths are different, the error uses /srv/db/checkm2_data/0.1.2/ but the working one uses /srv/db/checkm2_data/0.1.3/CheckM2_database

**Comment by julianzaugg** [comment]
Yes, it insisted on using `/srv/db/checkm2_data/0.1.2/`. Now that you point it out, I can see that whoever created the installation on our servers has set the location in `etc/conda/activate.d/aviary.sh:export CHECKM2DB=/srv/db/checkm2_data/0.1.2`. 
Though I would have thought a user could override by re-exporting for environment variable...not a big deal. Will close this issue now.

**Comment by rhysnewell** [comment]
You can reset environment variables using the aviary configure subcommand. The reason using export directly doesn't work is that environment variables within the conda environment take priority, hence why configure is required
