### ISSUE TITLE
Multi-Sample Functionality

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#67]
Hi Rhys,

I hope you've been well!

I have a suggestion for aviary (you've almost certainly thought of it before I'd guess!)

It would be great if there was a way to run aviary in multi-sample mode, with aviary cluster run on all the outputs once the pipeline is completed (e.g. with input specifying a csv file input with sample name, paths to read files).

I've written a little snakemake wrapper pipeline to do this with a parser function for my samples now, so I can re-purpose that if it would be helpful.

George

**Comment by rhysnewell** [comment]
Hi George,

This is a good request. I did have something implemented earlier on in development but it got left behind as I added more features. I think it is more important now to add it back in with aviary having the pangenome component within cluster now.

I've got some ideas in how to reimplement it, but perhaps you could send through your wrapper and I can pinch some ideas from it if they mesh nicely with the aviary code.

Cheers,
Rhys

**Comment by rhysnewell** [comment]
Hi George,

The main branch of Aviary now has a `aviary batch` subcommand that is available for testing. It seems to work on my end, but I'm still running some tests. Some example batch files can be found here: https://github.com/rhysnewell/aviary/tree/master/docs/_include/examples

For each line in a batch file, aviary will be run on the provided samples. By default it runs through the complete pipeline and then once all lines are finished it will run `aviary cluster` on them.

It lets you provide tsv and csv format files, as well as multiple read files per assembly and/or binning. You can set which workflow is to be run on all the runs in the batch. Let me know if there is anything else you'd want added and if this is the kind of functionality you were expecting.

Cheers,
Rhys

**Comment by gbouras13** [comment]
Gday Rhys,

I'll give it a go this week on my paired short read data and get back to you - it looks exactly what I'm after. The only possible thing I can thing that might be useful is that for the Clustering analysis, it might be useful to run the Cluster module multiple times for different ANI values. 

I found it useful to cluster at different ANI values for my MAGs - with 99% as default, there was no de-replication/clustering for my isolates. Instead, it makes sense in the context of my analysis for ANI thresholds like 80% (approx genus)  and 95% (approx species), so it would be nice if you could specify multiple ANI values so that the cluster step will run multiple times on these without re-running the entire aviary pipeline.

Separate question - what's the best way to cite Aviary for a presentation for now (just cite your GitHub - and you in the acknowledgements too!)? 

 George

**Comment by rhysnewell** [comment]
Hi George,

Ah yes, that's something I hadn't considered but I'll keep in mind for future releases. Shouldn't be too hard to implement, but I'll leave it for the next minor release as I just jumped the gun an released `v0.5.0`. In the mean time, it wouldn't be too hard for you to set up your own script that just runs `aviary cluster` multiple times on the output from the batch run with the differing ANI values.

Thank you! Yes, just cite the github now and chuck in my twitter & github links. Should be good enough for now.

Cheers,
Rhys

**Comment by gbouras13** [comment]
Hi Rhys,

Absolutely, I have done already so leave it for the future,  just a suggestion - I'm still trying to figure out how to decipher the pggb output to be honest!

George
