### ISSUE TITLE
Lack of --meta?

### ISSUE THREAD

**Issue by wwood** [rhysnewell/aviary#76]
Hi,

On line
https://github.com/rhysnewell/aviary/blob/9c27c7ef43aa7fadba7a6cbf6c0543dcc8371d41/aviary/modules/assembly/assembly.smk#L445

Shouldn't `--meta` be specified?

**Comment by rhysnewell** [comment]
I think when spades restarts from the last checkpoint it just re-uses the previous configuration which includes the --meta flag. --restart-from blocks off a whole lot of flags, so I assume that is why I didn't use it here, but might be worth double checking

**Comment by Ge0rges** [comment]
This is correct, `--restart-from` will take into account all basic options invariably which includes `--meta`.

**Comment by rhysnewell** [comment]
Thanks for confirming, I'll close this issue now
