### ISSUE TITLE
Configuration of aviary with hpc scheduler

### ISSUE THREAD

**Issue by Rridley7** [rhysnewell/aviary#77]
Hi, thanks for your work in developing this tool! I can see this being very useful for daily workflows. When I was trying out this tool, I had some difficulty with passing necessary information to the --snakemake-cmds option, e.g. a profile yaml containing my needed account and priority information for the scheduler (my scheduler is SLURM). The error I get is:

Error: profile given but no config.yaml found. Profile has to be given as either absolute path, relative path or name of a directory available in either /etc/xdg/snakemake or /storage/home/hcoda1/6/rridley3/.config/snakemake.

However, this file does certainly exist in the current directory.

**Comment by wwood** [comment]
Thanks for trying it out.

Just so we are on the same page, what was the argument supplied to --snakemake-cmds ? The more info the better here, but understand you might be constrained.

**Comment by rhysnewell** [comment]
Hi!

Yes, the full aviary command and string passed to `--snakemake-cmds` would be useful in trying to figure this out. I haven't really attempted to use a scheduler alongside aviary yet, I've only briefly tried sending jobs off via qsub but Snakemake spat out a bunch of errors. What I tend to do is instead just wrap the entire aviary command in a pbs script or slurm equivalent, and send that off to the scheduler

**Comment by Rridley7** [comment]
Thank you, yes I was looking specifically into the binning module from this workflow, which can be easily passed into a job. I first made a yaml file specifically related to cluster specifications:
`cluster: sbatch
    --cpus-per-task=24
    --mem=360G
    --ntasks-per-node=1
    -t=24:00:00
    --output={rule}_%A-%a.out
    --qos=inferno
    --output=logs/{rule}_{jobid}.out
    --error=logs/{rule}_{jobid}.err
jobs: 100
latency-wait: 15`

Saved as cluster-config.yaml I tried a few different commands, `--profile cluster-config.yaml`  or `--configfile cluster-config.yaml`, both gave errors.

**Comment by rhysnewell** [comment]
Would you please post the entire aviary command you tried to use?

**Comment by Rridley7** [comment]
The command was `aviary assemble -s 500 -b 50000 -1 11_5df59-t-.1.fq.gz -2 11_5df59-t-.2.fq.gz --dry-run --snakemake-cmds '--cluster sbatch --profile ./cluster_profile.yaml' ` 

I tried this same command with the various iterations of snakemake commands,
`--profile cluster-config.yaml` or `--configfile cluster-config.yaml` 
with and without `--cluster sbatch` command as well.

**Comment by wwood** [comment]
Thanks. I wonder if it might be easier (and work properly) if you put `cluster-config.yaml` in a folder in `/storage/home/hcoda1/6/rridley3/.config/snakemake` or specify an absolute path to `cluster-config.yaml` ?

**Comment by Rridley7** [comment]
This solved the issue, once I called the config file more properly it was able to execute successfully. Thanks!

**Comment by wwood** [comment]
Hoorah. Thanks for documenting here so others can come back to it.
