### ISSUE TITLE
template_config.yaml

### ISSUE THREAD

**Issue by yikiii** [rhysnewell/aviary#78]
can‘t make template_config.yaml

(aviary) [name@cluster ~]$ aviary recover -1 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_1.fq.gz -2 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_2.fq.gz --longreads /nfs6/public2/User/name/aviary_test/SRR17854520/SRR17854520_porechop.fastq.gz --long_read_type ont
10/24/2022 09:33:49 AM INFO: Time - 09:33:49 24-10-2022
10/24/2022 09:33:49 AM INFO: Command - /nfs3/public2/User/name/miniconda3/envs/aviary/bin/aviary recover -1 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_1.fq.gz -2 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_2.fq.gz --longreads /nfs6/public2/User/name/aviary_test/SRR17854520/SRR17854520_porechop.fastq.gz --long_read_type ont
10/24/2022 09:33:49 AM INFO: Version - 0.5.0
Traceback (most recent call last):
  File "/nfs3/public2/User/name/miniconda3/envs/aviary/bin/aviary", line 10, in <module>
    sys.exit(main())
  File "/nfs3/public2/User/name/miniconda3/envs/aviary/lib/python3.10/site-packages/aviary/aviary.py", line 1060, in main
    processor.make_config()
  File "/nfs3/public2/User/name/miniconda3/envs/aviary/lib/python3.10/site-packages/aviary/modules/processor.py", line 278, in make_config
    with open(template_conf_file) as template_config:
FileNotFoundError: [Errno 2] No such file or directory: '/nfs3/public2/User/name/miniconda3/envs/aviary/lib/python3.10/site-packages/aviary/modules/template_config.yaml'

Linux version 3.10.0-1062.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed Aug 7 18:08:02 UTC 2019

conda create -n aviary -c conda-forge -c bioconda aviary

**Comment by yikiii** [comment]
> can‘t make template_config.yaml
> 
> (aviary) [name@cluster ~]$ aviary recover -1 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_1.fq.gz -2 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_2.fq.gz --longreads /nfs6/public2/User/name/aviary_test/SRR17854520/SRR17854520_porechop.fastq.gz --long_read_type ont 10/24/2022 09:33:49 AM INFO: Time - 09:33:49 24-10-2022 10/24/2022 09:33:49 AM INFO: Command - /nfs3/public2/User/name/miniconda3/envs/aviary/bin/aviary recover -1 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_1.fq.gz -2 /nfs6/public2/User/name/aviary_test/SRR17843154/SRR17843154_2.fq.gz --longreads /nfs6/public2/User/name/aviary_test/SRR17854520/SRR17854520_porechop.fastq.gz --long_read_type ont 10/24/2022 09:33:49 AM INFO: Version - 0.5.0 Traceback (most recent call last): File "/nfs3/public2/User/name/miniconda3/envs/aviary/bin/aviary", line 10, in sys.exit(main()) File "/nfs3/public2/User/name/miniconda3/envs/aviary/lib/python3.10/site-packages/aviary/aviary.py", line 1060, in main processor.make_config() File "/nfs3/public2/User/name/miniconda3/envs/aviary/lib/python3.10/site-packages/aviary/modules/processor.py", line 278, in make_config with open(template_conf_file) as template_config: FileNotFoundError: [Errno 2] No such file or directory: '/nfs3/public2/User/name/miniconda3/envs/aviary/lib/python3.10/site-packages/aviary/modules/template_config.yaml'
> 
> Linux version 3.10.0-1062.el7.x86_64 ([mockbuild@kbuilder.bsys.centos.org](mailto:mockbuild@kbuilder.bsys.centos.org)) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Wed Aug 7 18:08:02 UTC 2019
> 
> conda create -n aviary -c conda-forge -c bioconda aviary

it looks like installed by conda lack Snakefile and template_config.yaml.

**Comment by wwood** [comment]
Hi,

This seems to be a consequence just of the bioconda version being out of date - 0.5.4 is the newest. Does installing via this method help? https://github.com/rhysnewell/aviary#option-2-install-from-pip

@rhysnewell I see there's some differences in the meta.yaml at bioconda-recipes and aviary.yml - do you know why?

Ta

**Comment by rhysnewell** [comment]
Yeah, looks like bioconda has stopped auto-updating aviary from pip for some reason. Not entirely sure why, but just install from pip for the moment.

@wwood Those aren't changes that I introduced, bioconda maintainers may have added in upper version restrictions for some reason but not one that I am aware of.

**Comment by yikiii** [comment]
> Hi,
> 
> This seems to be a consequence just of the bioconda version being out of date - 0.5.4 is the newest. Does installing via this method help? https://github.com/rhysnewell/aviary#option-2-install-from-pip
> 
> @rhysnewell I see there's some differences in the meta.yaml at bioconda-recipes and aviary.yml - do you know why?
> 
> Ta

thank you for your reply, i tried Option 3) Install from source, it works.
