### ISSUE TITLE
concoct hanging / --skip-binners concoct not working aviary 0.5.4

### ISSUE THREAD

**Issue by gbouras13** [rhysnewell/aviary#81]
Hi Rhys & Ben,

I've updated aviary (v0.5.4 via conda, install very smooth) and re-running it on some new data.

I've noticed two things.

Firstly, the concoct step seems to hang in the pipeline (for 8+ hours until I kill aviary). 

The output of the concoct_working directories are like:

-rw-rw-r-- 1 a1667917 a1667917      417 Nov 14 03:26 args.txt
-rw-rw-r-- 1 a1667917 a1667917  9351783 Nov 14 03:25 contigs_10K.bed
-rw-rw-r-- 1 a1667917 a1667917 61886740 Nov 14 03:25 contigs_10K.fa
-rw-rw-r-- 1 a1667917 a1667917  5753811 Nov 14 03:26 coverage_table.tsv
-rw-rw-r-- 1 a1667917 a1667917      768 Nov 14 03:26 log.txt
-rw-rw-r-- 1 a1667917 a1667917 12614645 Nov 14 03:26 original_data_gt1500.csv
-rw-rw-r-- 1 a1667917 a1667917   100661 Nov 14 03:26 PCA_components_data_gt1500.csv
-rw-rw-r-- 1 a1667917 a1667917  4352687 Nov 14 03:26 PCA_transformed_data_gt1500.csv

I can't really tell what the issues are from the log file.

2022-11-14 02:21:12,583:INFO:root:Successfully loaded composition data.
2022-11-14 02:21:12,648:INFO:root:Successfully loaded coverage data.
2022-11-14 02:21:14,232:INFO:root:Performed PCA, resulted in 59 dimensions
2022-11-14 02:21:14,747:INFO:root:Wrote original filtered data file.
2022-11-14 02:21:14,889:INFO:root:Wrote PCA transformed file.
2022-11-14 02:21:14,896:INFO:root:Wrote PCA components file.
2022-11-14 02:21:14,896:INFO:root:PCA transformed data.
2022-11-14 02:21:14,896:INFO:root:Will call vbgmm with parameters: data/concoct_working/, 400, 1500, 16, 500

It looks like this issue:

https://github.com/BinPro/CONCOCT/issues/290

Looks like a deadend unfortunately.

So secondly, I re-ran aviary and specified:

--skip-binners concoct

It wouldn't work - it would always still try and run concoct.

I've also tried (in combination as vamb always gives me issues, and sometimes rosella):

--skip-binners concoct vamb
--skip-binners concoct,vamb 
--skip-binners concoct rosella vamb
--skip-binners concoct,rosella,vamb 

and neither would work. 

Strangely, vamb (and rosella) would be skipped, but not concoct, so aviary would still run and hang on concoct.

George

**Comment by rhysnewell** [comment]
Hey George,

That seems a little odd. Would you be able to post the rules that aviary is deciding to run. Each rule should also output a reason that it was chosen to run, if you could post what reason snakemake is giving for concoct then that would also be helpful.

My hunch is that it has something to do with the output folder of concoct having some files in it or something. You could try deleting the concoct folder and then rerunning and see if it still reruns

Rhys

**Comment by gbouras13** [comment]
I've run it from scratch a couple of times (deleting all output and restarting aviary denovo) so there shouldn't be anything in the concoct_working directory.

I've attached a log with aviary --skip-binners concoct (you can see in the first line).

[aviary_concoct_error.log](https://github.com/rhysnewell/aviary/files/9998552/aviary_concoct_error.log)

George

**Comment by rhysnewell** [comment]
The error given by rosella is also of note in that log file. That kind of error usually occurs when the fasta index file wasn't generated properly for the assembly. Which is odd considering this looks like an almost complete aviary log, something weird must have happened.

First off, maybe try deleting the output binning output again and also the fasta index file for the assembly. And then run aviary with `--snakemake-param " --rerun-triggers mtime"` and see if that prevents concoct from running

**Comment by rhysnewell** [comment]
Alternatively, download latest release which contains a pretty major bug fix found by Sam, a colleague of mine and it will automatically apply the correct rerun trigger

**Comment by rhysnewell** [comment]
Skip binners should be full resolved as of https://github.com/rhysnewell/aviary/pull/101 closing this now, if you still have the problem please let us know
