### ISSUE TITLE
aviary stops at racon step by a potentially overwriting file issue when running in parallel

### ISSUE THREAD

**Issue by kk2302** [rhysnewell/aviary#94]
We are trying to run Aviary assemble (version 0.5.7) for two datasets in parallel.

Aviary stoped at the racon step (2 of 12 steps) with an error, potentially overwriting issue of input files.
We tried the following modification to overcome the issue, but not fixed yet.

1. set job number as 1 (i.e., parallel -j1)
2. set individual temp directory (i.e., --tmpdir /tmp/{}_tmp)

The command used was as follows:
```
ls *nanopore.fastq.gz | sed 's/-.*//' | parallel -j2 aviary assemble --longreads {}*.fastq.gz -1 /srv/projects/Japan_wastewater/illumina_reads_working/{}*R1_soapnuked.fastq.gz -2 /srv/projects/Japan_wastewater/illumina_reads_working/{}*R2_soapnuked.fastq.gz -t 25 -n 25 -m 730 --output /srv/projects/Japan_wastewater/aviary_outputs/aviaryAssemble_{} --conda-frontend "mamba" --tmpdir /tmp/{}_tmp '&>' /srv/projects/Japan_wastewater/aviary_outputs/aviaryAssemble_{}.log
```

and we got an error message as follows:

```
2 of 12 steps (17%) done
Removing temporary output data/flye/00-assembly.
Removing temporary output data/flye/10-consensus.
Removing temporary output data/flye/20-repeat.
Removing temporary output data/flye/30-contigger.
Removing temporary output data/flye/40-polishing.
Select jobs to execute...

[Mon Mar  6 16:01:08 2023]
rule polish_metagenome_racon:
    input: data/long_reads.fastq.gz, data/flye/assembly.fasta
    output: data/assembly.pol.rac.fasta
    jobid: 8
    benchmark: benchmarks/polish_metagenome_racon.benchmark.txt
    reason: Missing output files: data/assembly.pol.rac.fasta; Input files updated by another job: data/flye/assembly.fasta, data/long_reads.fastq.gz
    threads: 25
    resources: mem_mb=747520, mem_mib=712891, disk_mb=8044, disk_mib=7672, tmpdir=/tmp/181011KAG_tmp

Activating conda environment: ../../../../home/s4271512/.conda/envs/90cad926907712d009867af4936ebf10_
  File "<string>", line 1
    import sys; print(f'3.10')
                            ^
SyntaxError: invalid syntax
[Mon Mar  6 16:01:16 2023]
Error in rule polish_metagenome_racon:
    jobid: 8
    input: data/long_reads.fastq.gz, data/flye/assembly.fasta
    output: data/assembly.pol.rac.fasta
    conda-env: /srv/home/s4271512/.conda/envs/90cad926907712d009867af4936ebf10_
```

**Comment by rhysnewell** [comment]
Hi,

Seems like an odd issue. That error seems to occurring upon activation of the racon conda environment as that line of code that it is pointing too is not one of mine.

A couple of things to try and test:
1) Try activating that conda env i.e. `conda activate /home/s4271512/.conda/envs/90cad926907712d009867af4936ebf10_` and see if it activates.
** If it does activate, trying running racon i.e. `racon --help` or something similar
** If the error occurs upon activation, then delete the environment.
2) If the conda environment activates fine, and no error occurs when using racon just delete it anyway and let it rebuild itself.
** Please note that when rebuilding the conda environments, you can not run it in parallel. It has to be a single job. If you run aviary in parallel whilst it is trying to build environments, each aviary process will fight over who gets to make the environment resulting in corrupted environments.
3) Run on a single sample without using parallel at all.

If you have any questions, please let me know. I'd like to get to the bottom of this issue.

Cheers,
Rhys

**Comment by kk2302** [comment]
Hi Rhys,

We have done some further testing and have found that this error only occured when running concurrent aviary assemble jobs.
However, it also only occurred when run by my colleague.
When I run the same command with the same data, the assembly works fine.
We suspect that this newer version of aviary doesn't play well with some older environments that he has installed from pervious versions of aviary.
It's the only explanation we can think of.

Kengo and Steven
